apiVersion: batch/v1
kind: Job
metadata:
  name: "{{.Chart.Name}}-delete-configmap-{{.Release.Name}}"
  labels:
    app: bluecompute
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "13"
spec:
  template:
    metadata:
      name: "{{.Chart.Name}}-delete-configmap-{{.Release.Name}}"
      labels:
        app: bluecompute
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    spec:
      restartPolicy: Never
      containers:
      - name: delete-configmap
        image: ibmcase/kubectl:latest
        command: [ "/bin/bash", "-c" ]
        args: ["set -x; kubectl --namespace {{ .Release.Namespace }} delete configmaps bluemix-target || 
        echo \"bluemix-target already deleted\""]
        imagePullPolicy: IfNotPresent