replicaCount: 1
image:
  repository: quay.io/pires/docker-elasticsearch-kubernetes
  pullPolicy: IfNotPresent
  tag: 1.7.1-4

clustername: default-cluster

service:
  name: catalog-elasticsearch

labels:
  datastore: elasticsearch

resources:
  limits:
    memory: 700Mi
  requests:
    memory: 350Mi

secretName: binding-refarch-compose-for-elasticsearch

persistence:
  enabled: false
  existingName:
  volume:
    storageClass:
    size: 

global:
  persistence: 
    enabled: false
    volume: 
      storageClass:
      size: 


