apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.service.name }}
  labels:
    chart: '{{ .Release.Name }}-{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
    release: {{ .Release.Name }}
    implementation: microprofile
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-{{  .Chart.Name }}-selector"
        version: "current"
        release: {{ .Release.Name }}
        implementation: microprofile
    spec:
      containers:
      - name: "{{  .Chart.Name  }}"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
{{ if .Values.istio.enabled }}
{{ else }}
        readinessProbe:
          httpGet:
            path: /
            port: 9080
          initialDelaySeconds: 60
          timeoutSeconds: 60
        livenessProbe:
          httpGet:
            path: /health
            port: 9080
          initialDelaySeconds: 1500
          timeoutSeconds: 500
{{ end }}
        resources:
          requests:
            cpu: "{{ .Values.image.resources.requests.cpu }}"
            memory: "{{ .Values.image.resources.requests.memory }}"
        env:
          {{- if .Values.travis }}
          - name: jdbcURL
            value: "{{ .Values.jdbcURL }}"
          - name: rabbit
            value: "{{ .Values.minikubeIp }}"
          {{- else}}
          - name: jdbcURL
            value: "jdbc:mysql://{{ .Release.Name }}-{{ .Values.service.mysql }}:{{ .Values.service.sqlport }}/inventorydb?useSSL=false"
          - name: rabbit
            value: "{{ .Release.Name }}-{{ .Values.service.rabbitmq }}"
          {{- end }}
          - name: PORT
            value: "{{ .Values.service.servicePort }}"
          - name: APPLICATION_NAME
            value: "{{ .Release.Name }}"
          - name: zipkinHost
            value: "{{ .Release.Name }}-{{ .Values.service.zipkinName }}"
          - name: zipkinPort
            value: "{{ .Values.service.zipkinPort }}"
