apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "inventory.fullname" . }}
  labels:
    {{- include "inventory.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        {{- include "inventory.labels" . | indent 8 }}
    spec:
      initContainers:
      {{- include "inventory.mysql.initcontainer" . | indent 6 }}
      containers:
      - name: inventory
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          protocol: TCP
        env:
        {{- include "inventory.environmentvariables" . | indent 8 }}
        {{- include "inventory.mysql.environmentvariables" . | indent 8 }}
        resources:
{{ toYaml .Values.resources | indent 10 }}