{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "inventory.fullname" . }}
  {{- if .Values.ingress.ibmCloud.redirectToHTTPS }}
  annotations:
   ingress.bluemix.net/redirect-to-https: "True"
  {{- end }}
  labels:
    {{- include "inventory.labels" . | indent 4 }}
spec:
  {{- if .Values.tls.enabled }}
  tls:
  - hosts:
    {{- if .Values.ingress.hostname }}
    - {{ .Values.ingress.hostname }}
    {{- else }}
    - {{ template "inventory.fullname" . }}
    {{- end }}
    {{- if .Values.tls.secretName }}
    secretName: {{ .Values.tls.secretName }}
    {{- else }}
    secretName: {{ .Release.Name }}-{{ .Chart.Name }}-tls
    {{- end }}
  {{- end }}
  rules:
  {{- if .Values.ingress.hostname }}
  - host: {{ .Values.ingress.hostname }}
  {{- else }}
  - host: {{ template "inventory.fullname" . }}
  {{- end }}
    http:
      paths:
      - path: {{ .Values.ingress.path }}
        backend:
          serviceName: {{ template "inventory.fullname" . }}
          servicePort: {{ .Values.service.externalPort }}
{{- end }}