# Server configuration
server:
  context-path: /micro
  port: 8081

# Spring properties
spring:
  application:
     name: catalog-microservice

# Elasticsearch
elasticsearch:
  url: http://localhost:9200
  user:
  password:
  index: micro
  doc_type: items
