
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  selector: 
    app: bluecompute
    tier: backend
    micro: inventory
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector: 
    app: bluecompute
    tier: backend
    micro: inventory