apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.service.name }}
  labels:
    chart: '{{ .Release.Name }}-{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
    implementation: microprofile
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-{{  .Chart.Name }}-selector"
        version: "current"
        implementation: microprofile
    spec:
      containers:
      - name: "{{  .Chart.Name  }}"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
{{ if .Values.istio.enabled }}
{{ else }}
        readinessProbe:
          httpGet:
            path: /
            port: 9080
          initialDelaySeconds: 60
          timeoutSeconds: 60
        livenessProbe:
          httpGet:
            path: /health
            port: 9080
          initialDelaySeconds: 60
          timeoutSeconds: 60
{{ end }}
        resources:
          requests:
            cpu: "{{ .Values.image.resources.requests.cpu }}"
            memory: "{{ .Values.image.resources.requests.memory }}"
        env:
          - name: elasticsearch_url
            value: "http://{{ .Release.Name }}-catalog-elasticsearch:9200"
          - name: inventory_health
            value: "http://{{ .Release.Name }}-inventory:9080/health"
          - name: PORT
            value: "{{ .Values.service.servicePort }}"
          - name: APPLICATION_NAME
            value: "{{ .Release.Name }}"
          - name: IBM_APM_SERVER_URL
            valueFrom:
              secretKeyRef:
                name: apm-server-config
                key: ibm_apm_server_url
                optional: true
          - name: IBM_APM_KEYFILE
            valueFrom:
              secretKeyRef:
                name: apm-server-config
                key: ibm_apm_keyfile
                optional: true
          - name: IBM_APM_KEYFILE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: apm-server-config
                key: ibm_apm_keyfile_password
                optional: true
          - name: IBM_APM_INGRESS_URL
            valueFrom:
              secretKeyRef:
                name: apm-server-config
                key: ibm_apm_ingress_url
                optional: true
          - name: IBM_APM_ACCESS_TOKEN
            valueFrom:
              secretKeyRef:
                name: apm-server-config
                key: ibm_apm_access_token
                optional: true
        volumeMounts:
        - name: config-volume
          mountPath: /opt/ibm/wlp/usr/shared
      volumes:
      - name: config-volume
        configMap:
          name: {{ .Release.Name }}-{{ .Chart.Name }}-config
