{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  #annotations:
  #  ingress.kubernetes.io/rewrite-target: /
  labels:
    release: {{ .Release.Name | quote }}
    chart: {{ .Chart.Name}}-{{ .Chart.Version }}
spec:
  {{- if .Values.tls.enabled }}
  tls:
  - hosts:
    {{- if .Values.ingress.hostname }}
    - {{ .Values.ingress.hostname }}
    {{- else }}
    - {{ template "catalogServiceName" . }}
    {{- end }}
    {{- if .Values.tls.secretName }}
    secretName: {{ .Values.tls.secretName }}
    {{- else }}
    secretName: {{ .Release.Name }}-{{ .Chart.Name }}-tls
    {{- end }}
  {{- end }}
  rules:
  {{- if .Values.ingress.hostname }}
  - host: {{ .Values.ingress.hostname }}
  {{- else }}
  - host: {{ template "catalogServiceName" . }}
  {{- end }}
    http:
      paths:
      - path: {{ .Values.ingress.path }}
        backend:
          serviceName: {{ template "catalogServiceName" . }}
          servicePort: {{ .Values.service.externalPort }}
{{- end }}