{{ if .Values.istio.enabled }}
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: "{{ .Release.Name }}-{{  .Chart.Name }}-default"
spec:
  destination:
    name: {{ .Release.Name }}-{{ .Values.service.name }}
  precedence: 1
  route:
  - labels:
      version: "current"
      release: {{ .Release.Name }}
      implementation: microprofile
    weight: {{ .Values.istio.weight }}
{{ if .Values.base.enabled }}
  - labels:
      version: "base"
      release: {{ .Release.Name }}
      implementation: microprofile
    weight: {{ .Values.base.weight }}
{{ end }}
{{ end }}
