apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: bluecompute
    micro: mysql
    tier: data
    release: {{.Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  template:
    metadata:
      labels:
        app: bluecompute
        micro: mysql
        tier: data
        release: {{.Release.Name | quote }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    spec:
      containers:
      - name: inventory-backup-container
        image: patrocinio/ibm-backup-restore
        command: ["/bin/bash"]
        args: ["-c", "/backup_restore/vbackup"]
        env:
        - name: BACKUP_NAME
          value: patrocinio-inventory-mysql
        - name: BACKUP_DIRECTORY
          value: /var/lib/mysql
        - name: RESTORE_DIRECTORY
          value: /var/lib/mysql
        - name: PROJECTID
          value: 0f64bd4bd6da481b8c8da6aed68a894d
        - name: REGION
          value: dallas
        - name: USERID
          value: 266d2076dfa94512ab6133f1f2bebce5
        - name: PASSWORD
          value: M!KiQ3.Cp4r3WVdK
        - name: SCHEDULE_TYPE
          value: periodic
        - name: SCHEDULE_INFO
          value: daily
        - name: BACKUP_TYPE
          value: incremental
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: data
      volumes:
      - name: data
        hostPath:
          path: /var/lib/mysql-inv2
